WebStrike/Models/Actor.cs
using System.ComponentModel.DataAnnotations;

namespace WebStrike.Models {
    public class Actor {
        [Key]
        public int Id { get; set; }
        public string? ProfilePictureURL { get; set; }
        public string? FullName { get; set; }
        public string? Bio { get; set; }

        //Relationships
        public List<Actor_Movie>? Actors_Movies { get; set; }
    }
}

WebStrike/Models/Actor_Movie.cs
namespace WebStrike.Models {
    public class Actor_Movie {
        public int MovieId { get; set; }
        public Movie? Movie { get; set; }

        public int ActorId { get; set; }
        public Actor? Actor { get; set; }
    }
}

WebStrike/Models/Cinema.cs
using System.ComponentModel.DataAnnotations;

namespace WebStrike.Models {
    public class Cinema {
        [Key]
        public int Id { get; set; }
        public string? Logo { get; set; }
        public string? Name { get; set; }
        public string? Description { get; set; }

        //Relationships
        public List<Movie>? Movies { get; set; }
    }
}

WebStrike/Models/ErrorViewModel.cs
namespace WebStrike.Models {
    public class ErrorViewModel {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebStrike/Models/Movie.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using WebStrike.Data.Enums;

namespace WebStrike.Models {
    public class Movie {
        [Key]
        public int Id { get; set; }

        public string? Name { get; set; }
        public string? Description { get; set; }
        public double Price { get; set; }
        public string? ImageURL { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public MovieCategory MovieCategory { get; set; }

        //Relationships
        public List<Actor_Movie>? Actors_Movies { get; set; }

        //Cinema
        public int CinemaId { get; set; }
        [ForeignKey("CinemaId")]
        public Cinema? Cinema { get; set; }

        //Producer
        public int ProducerId { get; set; }
        [ForeignKey("ProducerId")]
        public Producer? Producer { get; set; }
    }
}

WebStrike/Models/Producer.cs
using System.ComponentModel.DataAnnotations;

namespace WebStrike.Models {
    public class Producer {
        [Key]
        public int Id { get; set; }
        public string? ProfilePictureURL { get; set; }
        public string? FullName { get; set; }
        public string? Bio { get; set; }

        //Relationships
        public List<Movie>? Movies { get; set; }
    }
}

WebStrike/Controllers/ActorsController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebStrike.Controllers {
    public class ActorsController : Controller {
        public IActionResult Index() {
            return View();
        }
    }
}

WebStrike/Controllers/ApiController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebStrike.Data;
using WebStrike.Models;


namespace WebStrike.Controllers {

    [Route("api/[controller]")]
    [ApiController]
    public class ApiController : ControllerBase {
        private readonly ApplicationDbContext _context;

        public ApiController(ApplicationDbContext context ) {  
            _context = context;
        }
        [HttpGet("GetActors")]
        public async Task<List<Actor>> GetActors() {
            return await _context.Actors.ToListAsync();
        }

        [HttpGet("GetActor/{id}")]
        public async Task<IActionResult> GetActorsById(int id) {
            var actor = await _context.Actors.FindAsync(id);
            return actor== null ? NotFound() : Ok(actor);
        }

        [HttpGet("GetProducers")]
        public async Task<List<Producer>> GetProducers() {
            return await _context.Producers.ToListAsync();
        }
        [HttpGet("GetCinemas")]
        public async Task<List<Cinema>> GetCinemas() {
            return await _context.Cinemas.ToListAsync();
        }
        [HttpGet("GetMovies")]
        public async Task<List<Movie>> GetMovies() {
            return await _context.Movies.Include(n => n.Cinema).ToListAsync();
        }
    }
}

WebStrike/Controllers/CinemasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebStrike.Data;

namespace WebStrike.Controllers {
    public class CinemasController : Controller {
        private readonly ApplicationDbContext _context;
        public CinemasController(ApplicationDbContext context) {
            _context = context;
        }
        public async Task<IActionResult> Index() {
            var data = await _context.Cinemas.ToListAsync();

            return View();
        }
    }
}

WebStrike/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebStrike.Models;

namespace WebStrike.Controllers {
    public class HomeController : Controller {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger) {
            _logger = logger;
        }

        public IActionResult Index() {
            return View();
        }
    }
}

WebStrike/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebStrike.Data;

namespace WebStrike.Controllers {
    public class MoviesController : Controller {
        private readonly ApplicationDbContext _context;
        public MoviesController(ApplicationDbContext context) {
            _context = context;
        }
        public async Task<IActionResult> Index() {
            var data = await _context.Movies.Include(n => n.Cinema).ToListAsync();

            return View();
        }
    }
}

WebStrike/Controllers/ProducersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebStrike.Data;

namespace WebStrike.Controllers {
    public class ProducersController : Controller {
        private readonly ApplicationDbContext _context;
        public ProducersController(ApplicationDbContext context) {
            _context = context;
        }
        public async Task<IActionResult> Index() {
            var data = await _context.Producers.ToListAsync();

            return View();
        }
    }
}

WebStrike/Views/Actors/Index.cshtml
@{
    ViewData["Title"] = "List of Actors";
}

    <div class="row">
        <div id="actorsDiv" class="col-md-8 offset-md-2">
        <table class="table">
            <thead id="tableHead">
                <tr class="text-center">
                    <th>Profile Picture</th>
                    <th>Full Name</th>
                    <th>Bio</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody id="tableBody">
            </tbody>
        </table>
        </div>
    </div>
@section scripts {
    <script type="module" src="~/js/pages/actors.js"></script>
    }

WebStrike/Views/Cinemas/Index.cshtml
@{
    ViewData["Title"] = "List of Cinemas";
}

<div class="row">
    <div id="cinemasDiv" class="col-md-8 offset-md-2">
        <table class="table">
            <thead id="tableHead">
                <tr class="text-center">
                    <th>Logo</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody id="tableBody">
            </tbody>
        </table>
    </div>
</div>
@section scripts {
    <script type="module" src="~/js/pages/cinemas.js"></script>
    }

WebStrike/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
<div id="ts-example">
    <br />
    <button type="button" class="btn btn-primary btn-md" onclick="TSButton()">
        Click Me
    </button>
</div>

WebStrike/Views/Movies/Index.cshtml
@{
    ViewData["Title"] = "List of Movies";
}


<div class="row" id="card">
</div>
@section scripts {
    <script type="module" src="~/js/pages/movies.js"></script>
    <script src="~/js/dayjs/dayjs.js"></script>
    }

WebStrike/Views/Producers/Index.cshtml
@{
    ViewData["Title"] = "List of Producers";
}

<div class="row">
    <div id="producersDiv" class="col-md-8 offset-md-2">
        <table class="table">
            <thead id="tableHead">
                <tr class="text-center">
                    <th>Profile Picture</th>
                    <th>Full Name</th>
                    <th>Bio</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody id="tableBody">
            </tbody>
        </table>
    </div>
</div>
@section scripts {
    <script type="module" src="~/js/pages/producers.js"></script>
    }

WebStrike/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebStrike</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="./css/script.css" />
    <link rel="stylesheet" href="~/WebStrike.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebStrike</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Movies" asp-action="Index"><i class="bi bi-film"></i> Movies</a>
                        </li>
                        @*@if (User.Identity.IsAuthenticated && User.IsInRole("Admin")) {*@
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" type="button" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-gear"></i> Management
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Cinemas" asp-action="Index"><i class="bi bi-camera-reels"></i> Cinemas</a>
                                    <a class="dropdown-item" asp-controller="Producers" asp-action="Index"><i class="bi bi-headset"></i> Producers</a>
                                    <a class="dropdown-item" asp-controller="Actors" asp-action="Index"><i class="bi bi-person-square"></i> Actors</a>
                                </div>
                            </li>
                        @*}*@
                    </ul>
                    <div class="filter">
                        <input id="filterInput" type="text"  placeholder="Search for a movie..." aria-label="Recipient's username">
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebStrike
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/app.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>